services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: jackypao
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

volumes:
  db:
