// <auto-generated />
using System;
using EmployeeManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeManagement.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914034506_AddEmployeeAuthentication")]
    partial class AddEmployeeAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Api.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Department")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Unassigned")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<DateOnly>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("hire_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("EMPLOYEE")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Department")
                        .HasDatabaseName("employee_department_index");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("employee_email_unique");

                    b.HasIndex("HireDate", "Id")
                        .HasDatabaseName("employee_hire_date_id_index");

                    b.ToTable("employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Age = 36,
                            Department = "Engineering",
                            Email = "ada.lovelace@example.com",
                            Gender = "FEMALE",
                            HireDate = new DateOnly(2022, 1, 10),
                            Name = "Ada Lovelace",
                            PasswordHash = "pbkdf2-sha512$210000$OZfEv+OZUJTcIIdtAVyYXg==$a8oOcVTMayfvFrgxau91wst5Gfpz+oYJSSJXKZB7/mE=",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = -2,
                            Age = 40,
                            Department = "Engineering",
                            Email = "grace.hopper@example.com",
                            Gender = "FEMALE",
                            HireDate = new DateOnly(2021, 6, 15),
                            Name = "Grace Hopper",
                            PasswordHash = "pbkdf2-sha512$210000$AliQAXJgMCXOJZ+2upmC9A==$ph1o4NERokHaYu5MMq+4gimFoKM0AEiRU94J/Ss/CW8=",
                            Role = "EMPLOYEE"
                        },
                        new
                        {
                            Id = -3,
                            Age = 45,
                            Department = "Human Resources",
                            Email = "peter.drucker@example.com",
                            Gender = "MALE",
                            HireDate = new DateOnly(2020, 3, 20),
                            Name = "Peter Drucker",
                            PasswordHash = "pbkdf2-sha512$210000$9Tk38apCOflFaJ3P8v90SA==$PN0Up22LpjNC9IALuVkNUoAW7lhN6na6N9S8DJDVvuM=",
                            Role = "EMPLOYEE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
